# %load template_config.yml
# example of bot_entity configuration

transaction_amount: 50
stop_loss: 10

exchange: binance
currency_pairs:
  - ETH/USDT
  - DOT/USDT
ticker: 1h
# start_time: 2021-11-11
last_n_candles: 400
sell_all: False
timeout: 30
max_open_trades: 5
